//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountCustomer()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string NGAY_SINH { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string PHONE_NUMBER { get; set; }
        public int STATUS { get; set; }
        public string NAME { get; set; }
        public string DIACHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
