//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDVKH
    {
        public int ID { get; set; }
        public int MaDV { get; set; }
        public int MaKH { get; set; }
        public int MaNV { get; set; }
        public string TenQuyTrinh { get; set; }
        public int Buoi { get; set; }
        public string ThoiGianTu { get; set; }
        public string ThoiGianDen { get; set; }
        public string NgayThucHien { get; set; }
        public int Checked { get; set; }
        public string HINH_ANH { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual USER USER { get; set; }
    }
}
