//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.ChiTietDVKHs = new HashSet<ChiTietDVKH>();
            this.DanhSachDVKHs = new HashSet<DanhSachDVKH>();
        }
    
        public int ID { get; set; }
        public string TEN_DICH_VU { get; set; }
        public string LOAI_DICH_VU { get; set; }
        public string MOTA_DICH_VU { get; set; }
        public decimal GIA_DICH_VU { get; set; }
        public int SO_NGAY_THUC_HIEN { get; set; }
        public string HINH_ANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDVKH> ChiTietDVKHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachDVKH> DanhSachDVKHs { get; set; }
    }
}
