//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
        }
    
        public int ID { get; set; }
        public string TENSP { get; set; }
        public string LOAISP { get; set; }
        public string MOTA_SP { get; set; }
        public decimal GIA { get; set; }
        public System.DateTime NAM_SAN_XUAT { get; set; }
        public System.DateTime NAM_HET_HAN { get; set; }
        public string HINH_ANH { get; set; }
        public int SO_LUONG { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
    }
}
